name: Publish shared library

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master

jobs:
  lint:
    uses: ToolOps/reusable-workflows/.github/workflows/helm-lint.yml@v0.0.40
  publish:
    uses: ToolOps/reusable-workflows/.github/workflows/helm-release.yml@v0.0.40
    with:
      chart_name: shared-library
    secrets: inherit
