name: Publish shared library

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master

jobs:
  lint:
    uses: ToolOps/reusable-workflows/.github/workflows/helm-lint-workflow.yml@v0.0.16
  publish:
    uses: ToolOps/reusable-workflows/.github/workflows/helm-release-workflow.yml@debug
    with:
      chart_name: shared-library
    secrets: inherit
