name: Publish shared library

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master

jobs:
  publish:
    uses: ToolOps/reusable-workflows/.github/workflows/helm-release-workflow.yml@main
    with:
      chart_name: shared-library
    secrets: inherit